name: emanoelviana

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  remixicon: ^1.2.0
  gap: ^3.0.1
  firebase_core: ^2.32.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/profile/

  fonts:
    - family: Roobert
      fonts:
        - asset: assets/fonts/roobert/RoobertTRIAL-Light.ttf
          weight: 300
        - asset: assets/fonts/roobert/RoobertTRIAL-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roobert/RoobertTRIAL-Regular.ttf
          weight: 400
        - asset: assets/fonts/roobert/RoobertTRIAL-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/roobert/RoobertTRIAL-Medium.ttf
          weight: 500
        - asset: assets/fonts/roobert/RoobertTRIAL-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roobert/RoobertTRIAL-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roobert/RoobertTRIAL-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/roobert/RoobertTRIAL-Bold.ttf
          weight: 700
        - asset: assets/fonts/roobert/RoobertTRIAL-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roobert/RoobertTRIAL-Heavy.ttf
          weight: 800
        - asset: assets/fonts/roobert/RoobertTRIAL-HeavyItalic.ttf
          weight: 800
          style: italic
